language: ruby
sudo: false
services:
  - mongodb
rvm:
  - 2.0
  - 2.1
  - 2.2
  # - rbx
gemfile:
  - gemfiles/rails.3.2.activerecord.gemfile
  - gemfiles/rails.3.2.activerecord.kaminari.gemfile
  - gemfiles/rails.3.2.activerecord.will_paginate.gemfile
  - gemfiles/rails.4.0.activerecord.gemfile
  - gemfiles/rails.4.0.activerecord.kaminari.gemfile
  - gemfiles/rails.4.0.activerecord.will_paginate.gemfile
  - gemfiles/rails.4.1.activerecord.gemfile
  - gemfiles/rails.4.1.activerecord.kaminari.gemfile
  - gemfiles/rails.4.1.activerecord.will_paginate.gemfile
  - gemfiles/rails.4.2.activerecord.gemfile
  - gemfiles/rails.4.2.activerecord.kaminari.gemfile
  - gemfiles/rails.4.2.activerecord.will_paginate.gemfile
  - gemfiles/rails.4.0.mongoid.gemfile
  - gemfiles/rails.4.0.mongoid.kaminari.gemfile
  - gemfiles/rails.4.0.mongoid.will_paginate.gemfile
  - gemfiles/rails.4.1.mongoid.gemfile
  - gemfiles/rails.4.1.mongoid.kaminari.gemfile
  - gemfiles/rails.4.1.mongoid.will_paginate.gemfile
  - gemfiles/rails.4.2.mongoid.gemfile
  - gemfiles/rails.4.2.mongoid.kaminari.gemfile
  - gemfiles/rails.4.2.mongoid.will_paginate.gemfile
  - gemfiles/sequel.4.28.gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails.3.2.activerecord.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails.3.2.activerecord.kaminari.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails.3.2.activerecord.will_paginate.gemfile
before_install:
  - curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.2.tar.gz | tar xz -C /tmp
before_script:
  - TEST_CLUSTER_COMMAND="/tmp/elasticsearch-1.7.2/bin/elasticsearch" rake elasticsearch:start
